use_frameworks!

platform :ios, '8.0'

target 'WPChained_Example' do
  pod 'WPChained', :path => '../'

  target 'WPChained_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
